version: 0.2
env:
  variables:
    IMAGE_HOST: ''
    # IMAGE_NAME: weseek/growi
    IMAGE_NAME: weseek/growi-codebuild-test
    SOURCE_TAG_AMD64: latest-amd64
    SOURCE_TAG_ARM64: latest-arm64
    TAGS: latest
    SECRETS_JSON_KEY: DOCKER_REGISTRY_PASSWORD # DOCKER_REGISTRY_PASSWORD or DOCKER_REGISTRY_ON_GITHUB_PASSWORD
  secrets-manager:
    DOCKER_REGISTRY_PASSWORD: growi/official-image-builder:$SECRETS_JSON_KEY
phases:
  pre_build:
    commands:
      - echo ${DOCKER_REGISTRY_PASSWORD} | docker login --username wsmoogle --password-stdin ${IMAGE_HOST}
  build:
    commands:
      - export IMAGE="${IMAGE_HOST}${IMAGE_HOST:+/}${IMAGE_NAME}"
      - bash ./packages/app/docker/codebuild/create-manifests.sh
          --target-image "${IMAGE}"
          --tags "${TAGS}"
          --source-manifests "${IMAGE}:${SOURCE_TAG_AMD64} ${IMAGE}:${SOURCE_TAG_ARM64}"
