version: 0.2
env:
  variables:
    BUILD_NUM: 0
    SECRETS_NAME: ''
    IMAGE_HOST: ''
    IMAGE_NAME: weseek/growi
    TAG_VERSION: latest
    SECRETS_JSON_KEY: DOCKER_REGISTRY_PASSWORD # DOCKER_REGISTRY_PASSWORD or DOCKER_REGISTRY_ON_GITHUB_PASSWORD
  secrets-manager:
    DOCKER_REGISTRY_PASSWORD: ${SECRETS_NAME}:${SECRETS_JSON_KEY}
phases:
  pre_build:
    commands:
      - echo ${DOCKER_REGISTRY_PASSWORD} | docker login --username wsmoogle --password-stdin ${IMAGE_HOST}
  build:
    commands:
      - export IMAGE_TAG="${IMAGE_HOST}${IMAGE_HOST:+/}${IMAGE_NAME}:${TAG_VERSION}"
      - export IMAGE_TAG_AMD64="${IMAGE_HOST}${IMAGE_HOST:+/}${IMAGE_NAME}:${TAG_VERSION}.BUILD.${BUILD_NUM}-amd64"
      - export IMAGE_TAG_ARM64="${IMAGE_HOST}${IMAGE_HOST:+/}${IMAGE_NAME}:${TAG_VERSION}.BUILD.${BUILD_NUM}-arm64"
      - docker manifest create $IMAGE_TAG $IMAGE_TAG_AMD64 $IMAGE_TAG_ARM64

  post_build:
    commands:
      - docker manifest push $IMAGE_TAG
