version: 0.2
batch:
  fast-fail: true
  build-graph:
    # build
    - identifier: build_amd64
      buildspec: packages/app/docker/codebuild/buildspec-image.yml
      env:
        image: aws/codebuild/standard:6.0
        type: LINUX_CONTAINER
        variables:
          TAG_VERSION: latest
          TAG_SUFFIX: amd64
    - identifier: build_arm64
      buildspec: packages/app/docker/codebuild/buildspec-image.yml
      env:
        image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
        type: ARM_CONTAINER
        variables:
          TAG_VERSION: latest
          TAG_SUFFIX: arm64
    # create manifest
    - identifier: create_manifest_dockerhub
      buildspec: packages/app/docker/codebuild/buildspec-manifest.yml
      env:
        variables:
          SECRETS_JSON_KEY: DOCKER_REGISTRY_PASSWORD
          SOURCE_TAG_AMD64: latest-amd64
          SOURCE_TAG_ARM64: latest-arm64
          TAGS: latest
      depend-on:
        - build_amd64
        - build_arm64
    # - identifier: create_manifest_ghcr
    #   buildspec: packages/app/docker/codebuild/buildspec-manifest.yml
    #   env:
    #     variables:
    #       IMAGE_HOST: ghcr.io
    #       SECRETS_JSON_KEY: DOCKER_REGISTRY_ON_GITHUB_PASSWORD
    #       SOURCE_MANIFESTS: ghcr.io/weseek/growi/latest-amd64 ghcr.io/weseek/growi/latest-arm64
    #       TAGS: latest
    #   depend-on:
    #     - build_amd64
    #     - build_arm64
