version: 0.2
env:
  variables:
    IMAGE_HOST: ''
    IMAGE_NAME: weseek/growi
    TAG_TMP: codebuildtmp
    TAGS: latest
    SECRETS_JSON_KEY: DOCKER_REGISTRY_PASSWORD # DOCKER_REGISTRY_PASSWORD or DOCKER_REGISTRY_ON_GITHUB_PASSWORD
  secrets-manager:
    DOCKER_REGISTRY_PASSWORD: growi/official-image-builder:$SECRETS_JSON_KEY
phases:
  pre_build:
    commands:
      - echo ${DOCKER_REGISTRY_PASSWORD} | docker login --username wsmoogle --password-stdin ${IMAGE_HOST}
  build:
    commands:
      - export TMP_TAG="${IMAGE_HOST}${IMAGE_HOST:+/}${IMAGE_NAME}:${TAG_TMP}"
      - export TMP_TAG_AMD64="${IMAGE_HOST}${IMAGE_HOST:+/}${IMAGE_NAME}:${TAG_TMP}-amd64"
      - export TMP_TAG_ARM64="${IMAGE_HOST}${IMAGE_HOST:+/}${IMAGE_NAME}:${TAG_TMP}-arm64"
      - docker manifest create $TMP_TAG $TMP_TAG_AMD64 $TMP_TAG_ARM64

  post_build:
    commands:
      - docker manifest push ${IMAGE_TAG}
      # remove 
      # - docker run --rm -it lumir/remove-dockerhub-tag --user wsmoogle --pass ${DOCKER_REGISTRY_PASSWORD} ${TMP_TAG} ${TMP_TAG_AMD64} ${TMP_TAG_ARM64}
