name: Release Docker Images for RC

on:
  push:
    branches:
      - rc/**


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  determine-tags:
    runs-on: ubuntu-latest

    outputs:
      TAGS: ${{ steps.meta.outputs.tags }}

    steps:
    - uses: actions/checkout@v3

    - name: Retrieve information from package.json
      uses: myrotvorets/info-from-package-json-action@1.2.0
      id: package-json

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: weseek/growi-codebuild-test
        sep-tags: ','
        tags: |
          type=raw,value=${{ steps.package-json.outputs.packageVersion }}
          type=raw,value=${{ steps.package-json.outputs.packageVersion }}.{{sha}}


  build-image-rc:
    uses: weseek/growi/.github/workflows/reusable-app-build-image.yml@rc/6.0.3-with-codebuild
    with:
      image-name: weseek/growi-codebuild-test
      tag-temporary: latest-rc
    secrets:
      AWS_ROLE_TO_ASSUME_FOR_OIDC: ${{ secrets.AWS_ROLE_TO_ASSUME_FOR_OIDC }}


  publish-image-rc:
    needs: determine-tags

    strategy:
      matrix:
        registry: [docker.io, ghcr.io]

    uses: weseek/growi/.github/workflows/reusable-app-create-manifests.yml@rc/6.0.3-with-codebuild
    with:
      tags: ${{ needs.determine-tags.outputs.TAGS }}
      registry: ${{ matrix.registry }}
      image-name: weseek/growi-codebuild-test
      tag-temporary: latest-rc
    secrets:
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      DOCKER_REGISTRY_ON_GITHUB_PASSWORD: ${{ secrets.DOCKER_REGISTRY_ON_GITHUB_PASSWORD }}
